version: "3"

services:
  gitea:
    image: nicolasconstant/birdsitelive:latest
    container_name: birdsitelive
    environment:
      - Instance:Domain=example.com
      - Instance:AdminEmail=admin@example.com
      - Db:Type=postgres
      - Db:Host=db
      - Db:Name=birdsitelive
      - Db:User=birdsitelive
      - Db:Password=birdsitelive
      - Twitter:ConsumerKey=GET_VIA_DEVELOPER_TWITTER_COM
      - Twitter:ConsumerSecret=GET_VIA_DEVELOPER_TWITTER_COM
    networks:
      - default
      - birdsitelivenetwork    
    depends_on:
      - db

  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=birdsitelive
      - POSTGRES_PASSWORD=birdsitelive
      - POSTGRES_DB=birdsitelive
    networks:
      - birdsitelivenetwork
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  birdsitelivenetwork:
    external: false
  default:
    external:
      name: proxy
